title: Diabetic Retinopathy Detector
description: Classify fundus images using deep learning
link: https://github.com/ammar0211/retinopathy-classifier/

about:


  Diabetic retinopathy (DR), also known as diabetic eye disease, is a medical condition in which damage occurs to the retina due to diabetes mellitus. It is a leading cause of blindness. Diabetic retinopathy affects up to 80 percent of those who have had diabetes for 20 years or more. Diabetic retinopathy often has no early warning signs. Retinal (fundus) photography with manual interpretation is a widely accepted screening tool for diabetic retinopathy, with performance that can exceed that of in-person dilated eye examinations.
  
  This is a Diabetic Retinopathy Detector that detects Referrable Diabetic Retinopathy (RDR) using Deep Learning and was built with [fastai](docs.fast.ai)

code: hhttps://github.com/ammar0211/retinopathy-classifier

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/TDUlmUa.jpg
